import bcrypt from "bcryptjs";
import { PrismaNeon } from "@prisma/adapter-neon";
import { BadgeCategory, BadgeKind, PrismaClient, Role } from "@prisma/client";

const connectionString = process.env.DATABASE_URL ?? "";
const prisma = connectionString.includes(".neon.tech")
  ? new PrismaClient({ adapter: new PrismaNeon({ connectionString }) })
  : new PrismaClient();

// Event facilities — marked as home venues for calendar sync
const homeVenues = [
  "Camp Randall Stadium",
  "Kohl Center",
  "UW Field House",
  "LaBahn Arena",
  "Goodman Softball Complex",
  "Porter Boathouse",
  "McClimon Track/Soccer Complex",
  "Soderholm Family Aquatic Center",
  "Nielsen Tennis Stadium",
  "University Ridge",
  "Zimmer Championship Course",
];

// Training/support buildings — locations but not event venues
const supportFacilities = [
  "Stephen M. Bennett Student-Athlete Performance Center",
  "Fetzer Centers",
  "Golf Training Center",
  "McClain Facility",
];

// Legacy names for backwards compat
const legacyNames = {
  "Camp Randall": "Camp Randall Stadium",
  "McClimon Complex": "McClimon Track/Soccer Complex",
};

const badgeDefinitions = [
  {
    key: "first_checkout",
    name: "First Checkout",
    description: "Opened a first gear checkout.",
    icon: "PackageCheck",
    category: BadgeCategory.CHECKOUT,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 1,
    sortOrder: 10,
  },
  {
    key: "checkout_5",
    name: "Gear Regular",
    description: "Opened five gear checkouts.",
    icon: "PackageOpen",
    category: BadgeCategory.CHECKOUT,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    sortOrder: 20,
  },
  {
    key: "checkout_10",
    name: "Gear Hand",
    description: "Opened ten gear checkouts.",
    icon: "Boxes",
    category: BadgeCategory.CHECKOUT,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 10,
    sortOrder: 25,
  },
  {
    key: "checkout_25",
    name: "Gear Veteran",
    description: "Opened 25 gear checkouts.",
    icon: "Boxes",
    category: BadgeCategory.CHECKOUT,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 25,
    sortOrder: 30,
  },
  {
    key: "checkout_100",
    name: "Gear Master",
    description: "Opened 100 gear checkouts.",
    icon: "Warehouse",
    category: BadgeCategory.CHECKOUT,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 100,
    sortOrder: 40,
  },
  {
    key: "full_kit_no_misses",
    name: "Full Kit, No Misses",
    description: "Retired: replaced by automatic recognition or unused in practice.",
    icon: "Boxes",
    category: BadgeCategory.CHECKOUT,
    kind: BadgeKind.RULE,
    trigger: "manual",
    threshold: null,
    ruleKey: "full_kit_no_misses",
    active: false,
    sortOrder: 50,
  },
  {
    key: "on_time_1",
    name: "Punctual",
    description: "Returned a checkout on time.",
    icon: "Clock3",
    category: BadgeCategory.ON_TIME,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 1,
    ruleKey: "on_time_return",
    sortOrder: 110,
  },
  {
    key: "on_time_5",
    name: "Right on Time",
    description: "Returned five checkouts on time.",
    icon: "Clock3",
    category: BadgeCategory.ON_TIME,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 5,
    ruleKey: "on_time_return",
    sortOrder: 115,
  },
  {
    key: "on_time_10",
    name: "Reliable",
    description: "Returned ten checkouts on time.",
    icon: "CalendarCheck2",
    category: BadgeCategory.ON_TIME,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 10,
    ruleKey: "on_time_return",
    sortOrder: 120,
  },
  {
    key: "on_time_25",
    name: "Dependable",
    description: "Returned 25 checkouts on time.",
    icon: "CalendarCheck2",
    category: BadgeCategory.ON_TIME,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 25,
    ruleKey: "on_time_return",
    sortOrder: 125,
  },
  {
    key: "on_time_50",
    name: "Clockwork",
    description: "Returned 50 checkouts on time.",
    icon: "AlarmClockCheck",
    category: BadgeCategory.ON_TIME,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 50,
    ruleKey: "on_time_return",
    sortOrder: 130,
  },
  {
    key: "perfect_handoff",
    name: "Perfect Handoff",
    description: "Retired: replaced by automatic recognition or unused in practice.",
    icon: "ShieldCheck",
    category: BadgeCategory.ON_TIME,
    kind: BadgeKind.RULE,
    trigger: "manual",
    threshold: null,
    ruleKey: "perfect_handoff",
    active: false,
    sortOrder: 140,
  },
  {
    key: "first_scan",
    name: "Scanner",
    description: "Retired: every accepted kiosk scan is expected to succeed.",
    icon: "ScanLine",
    category: BadgeCategory.SCAN,
    kind: BadgeKind.COUNT,
    trigger: "scan:success",
    threshold: 1,
    active: false,
    sortOrder: 210,
  },
  {
    key: "scan_10",
    name: "Scan Ready",
    description: "Retired: every accepted kiosk scan is expected to succeed.",
    icon: "ScanLine",
    category: BadgeCategory.SCAN,
    kind: BadgeKind.COUNT,
    trigger: "scan:success",
    threshold: 10,
    active: false,
    sortOrder: 215,
  },
  {
    key: "scan_25",
    name: "Scan Pro",
    description: "Retired: every accepted kiosk scan is expected to succeed.",
    icon: "ScanSearch",
    category: BadgeCategory.SCAN,
    kind: BadgeKind.COUNT,
    trigger: "scan:success",
    threshold: 25,
    active: false,
    sortOrder: 220,
  },
  {
    key: "scan_50",
    name: "Scan Regular",
    description: "Retired: every accepted kiosk scan is expected to succeed.",
    icon: "ScanSearch",
    category: BadgeCategory.SCAN,
    kind: BadgeKind.COUNT,
    trigger: "scan:success",
    threshold: 50,
    active: false,
    sortOrder: 230,
  },
  {
    key: "scan_100",
    name: "Scan Master",
    description: "Retired: every accepted kiosk scan is expected to succeed.",
    icon: "QrCode",
    category: BadgeCategory.SCAN,
    kind: BadgeKind.COUNT,
    trigger: "scan:success",
    threshold: 100,
    active: false,
    sortOrder: 235,
  },
  {
    key: "zero_errors",
    name: "Clean Scanner",
    description: "Retired: clean scanning is the expected kiosk baseline.",
    icon: "ShieldCheck",
    category: BadgeCategory.SCAN,
    kind: BadgeKind.RULE,
    trigger: "scan:rule",
    threshold: 10,
    ruleKey: "zero_errors",
    active: false,
    sortOrder: 240,
  },
  {
    key: "first_shift",
    name: "On Duty",
    description: "Was assigned to a first completed event shift.",
    icon: "CalendarClock",
    category: BadgeCategory.SHIFT,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 1,
    sortOrder: 310,
  },
  {
    key: "shift_10",
    name: "Shift Regular",
    description: "Was assigned to ten completed event shifts.",
    icon: "CalendarDays",
    category: BadgeCategory.SHIFT,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 10,
    sortOrder: 320,
  },
  {
    key: "shift_25",
    name: "Crew Mainstay",
    description: "Was assigned to 25 completed event shifts.",
    icon: "CalendarDays",
    category: BadgeCategory.SHIFT,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 25,
    sortOrder: 325,
  },
  {
    key: "shift_50",
    name: "Shift Veteran",
    description: "Was assigned to 50 completed event shifts.",
    icon: "CalendarRange",
    category: BadgeCategory.SHIFT,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 50,
    sortOrder: 330,
  },
  {
    key: "first_trade",
    name: "Team Player",
    description: "Completed a first shift trade.",
    icon: "Handshake",
    category: BadgeCategory.TRADE,
    kind: BadgeKind.COUNT,
    trigger: "trade:completed",
    threshold: 1,
    sortOrder: 410,
  },
  {
    key: "trade_5",
    name: "Coverage Crew",
    description: "Completed five shift trades.",
    icon: "Handshake",
    category: BadgeCategory.TRADE,
    kind: BadgeKind.COUNT,
    trigger: "trade:completed",
    threshold: 5,
    sortOrder: 415,
  },
  {
    key: "trade_10",
    name: "Trade Expert",
    description: "Completed ten shift trades.",
    icon: "Repeat2",
    category: BadgeCategory.TRADE,
    kind: BadgeKind.COUNT,
    trigger: "trade:completed",
    threshold: 10,
    sortOrder: 420,
  },
  {
    key: "clutch_cover",
    name: "Clutch Cover",
    description: "Retired: replaced by automatic recognition or unused in practice.",
    icon: "Handshake",
    category: BadgeCategory.TRADE,
    kind: BadgeKind.RULE,
    trigger: "manual",
    threshold: null,
    ruleKey: "clutch_cover",
    active: false,
    sortOrder: 430,
  },
  {
    key: "streak_on_time_5",
    name: "On a Roll",
    description: "Returned five checkouts in a row on time.",
    icon: "Flame",
    category: BadgeCategory.STREAK,
    kind: BadgeKind.STREAK,
    trigger: "checkout:returned",
    threshold: 5,
    ruleKey: "on_time_return_streak",
    sortOrder: 510,
  },
  {
    key: "streak_on_time_10",
    name: "Locked In",
    description: "Returned ten checkouts in a row on time.",
    icon: "BadgeCheck",
    category: BadgeCategory.STREAK,
    kind: BadgeKind.STREAK,
    trigger: "checkout:returned",
    threshold: 10,
    ruleKey: "on_time_return_streak",
    sortOrder: 520,
  },
  {
    key: "streak_shifts_5",
    name: "Showing Up",
    description: "Retired: attendance-based shift badges are out of scope.",
    icon: "UserCheck",
    category: BadgeCategory.STREAK,
    kind: BadgeKind.STREAK,
    trigger: "shift:completed",
    threshold: 5,
    ruleKey: "retired_shift_attendance",
    active: false,
    sortOrder: 610,
  },
  {
    key: "streak_shifts_10",
    name: "Iron Schedule",
    description: "Retired: attendance-based shift badges are out of scope.",
    icon: "Trophy",
    category: BadgeCategory.STREAK,
    kind: BadgeKind.STREAK,
    trigger: "shift:completed",
    threshold: 10,
    ruleKey: "retired_shift_attendance",
    active: false,
    sortOrder: 620,
  },
  {
    key: "semester_streak",
    name: "Semester Streak",
    description: "Retired: replaced by automatic recognition or unused in practice.",
    icon: "CalendarCheck2",
    category: BadgeCategory.STREAK,
    kind: BadgeKind.RULE,
    trigger: "manual",
    threshold: null,
    ruleKey: "semester_streak",
    active: false,
    sortOrder: 630,
  },
  {
    key: "clean_loop",
    name: "Clean Loop",
    description: "Retired: replaced by automatic recognition or unused in practice.",
    icon: "BadgeCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "manual",
    threshold: null,
    ruleKey: "clean_loop",
    active: false,
    sortOrder: 710,
  },
  {
    key: "category_collector",
    name: "Category Collector",
    description: "Checked out gear from five different categories.",
    icon: "Trophy",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "category_collector",
    sortOrder: 720,
  },
  {
    key: "damage_free_10",
    name: "Careful Hands",
    description: "Returned ten checkouts with nothing damaged or missing.",
    icon: "ShieldCheck",
    category: BadgeCategory.ON_TIME,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 10,
    ruleKey: "damage_free_return",
    sortOrder: 150,
  },
  {
    key: "damage_free_50",
    name: "Immaculate",
    description: "Returned 50 checkouts with nothing damaged or missing.",
    icon: "BadgeCheck",
    category: BadgeCategory.ON_TIME,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 50,
    ruleKey: "damage_free_return",
    sortOrder: 160,
  },
  {
    key: "event_hero",
    name: "Event Hero",
    description: "Recognized by staff for standout help during an event.",
    icon: "UserCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "manual",
    threshold: null,
    ruleKey: "event_hero",
    sortOrder: 730,
  },
  {
    key: "rookie_run",
    name: "Rookie Run",
    description: "Retired: replaced by automatic recognition or unused in practice.",
    icon: "PackageCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "manual",
    threshold: null,
    ruleKey: "rookie_run",
    active: false,
    sortOrder: 740,
  },
  {
    key: "reliable_regular",
    name: "Reliable Regular",
    description: "Retired: replaced by automatic recognition or unused in practice.",
    icon: "CalendarDays",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "manual",
    threshold: null,
    ruleKey: "reliable_regular",
    active: false,
    sortOrder: 750,
  },
  {
    key: "above_and_beyond",
    name: "Above and Beyond",
    description: "Recognized for memorable help that made the operation better.",
    icon: "Trophy",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "manual",
    threshold: null,
    ruleKey: "above_and_beyond",
    sortOrder: 760,
  },
  {
    key: "power_player",
    name: "Power Player",
    description: "Checked out gear with batteries ten times.",
    icon: "BatteryCharging",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 10,
    ruleKey: "checkout_family_batteries",
    sortOrder: 770,
  },
  {
    key: "glass_class",
    name: "Glass Class",
    description: "Checked out lenses ten times.",
    icon: "Aperture",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 10,
    ruleKey: "checkout_family_lenses",
    sortOrder: 780,
  },
  {
    key: "sound_check",
    name: "Sound Check",
    description: "Checked out audio gear five times.",
    icon: "AudioLines",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "checkout_family_audio",
    sortOrder: 790,
  },
  {
    key: "rock_solid",
    name: "Rock Solid",
    description: "Checked out a tripod or gimbal three times.",
    icon: "Focus",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 3,
    ruleKey: "checkout_support",
    sortOrder: 800,
  },
  {
    key: "bright_spark",
    name: "Bright Spark",
    description: "Checked out lighting gear twice.",
    icon: "Lightbulb",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 2,
    ruleKey: "checkout_family_lighting",
    sortOrder: 810,
  },
  {
    key: "kitchen_sink",
    name: "Kitchen Sink",
    description: "Opened one checkout spanning five gear families.",
    icon: "LayoutGrid",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 1,
    ruleKey: "checkout_families_5",
    sortOrder: 820,
  },
  {
    key: "three_piece_suit",
    name: "Three-Piece Suit",
    description: "Checked out camera, lens, and audio gear together three times.",
    icon: "Combine",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 3,
    ruleKey: "checkout_full_rig",
    sortOrder: 830,
  },
  {
    key: "heavy_lifter",
    name: "Heavy Lifter",
    description: "Opened one checkout with at least 15 actual pieces.",
    icon: "Dumbbell",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 1,
    ruleKey: "checkout_items_15",
    sortOrder: 840,
  },
  {
    key: "road_tested",
    name: "Road Tested",
    description: "Was assigned to three completed away-event shifts.",
    icon: "BusFront",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 3,
    ruleKey: "shift_away_completed",
    sortOrder: 850,
  },
  {
    key: "before_sunrise",
    name: "Before Sunrise",
    description: "Was assigned to two completed shifts with call times before 7 a.m.",
    icon: "Sunrise",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 2,
    ruleKey: "shift_before_7",
    sortOrder: 860,
  },
  {
    key: "season_pass",
    name: "Season Pass",
    description: "Was assigned to completed shifts across four different sports.",
    icon: "Ticket",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 4,
    ruleKey: "shift_sports",
    sortOrder: 870,
  },
  {
    key: "utility_crew",
    name: "Utility Crew",
    description: "Was assigned to completed shifts in five different crew areas.",
    icon: "Shuffle",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 5,
    ruleKey: "shift_areas",
    sortOrder: 875,
  },
  {
    key: "doubleheader",
    name: "Doubleheader",
    description: "Was assigned to two or more completed shifts on the same day.",
    icon: "Repeat2",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 1,
    ruleKey: "shift_doubleheader_days",
    sortOrder: 880,
  },
  {
    key: "under_the_lights",
    name: "Under the Lights",
    description: "Was assigned to eight completed shifts that ran to 10 p.m. or later.",
    icon: "Sunset",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 8,
    ruleKey: "shift_after_22",
    sortOrder: 885,
  },
  {
    key: "deep_inventory",
    name: "Deep Inventory",
    description: "Checked out 25 different serialized items.",
    icon: "Warehouse",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 25,
    ruleKey: "checkout_distinct_assets",
    sortOrder: 890,
  },
  {
    key: "regular_rotation",
    name: "Regular Rotation",
    description: "Opened checkouts in six different weeks.",
    icon: "CalendarRange",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 6,
    ruleKey: "checkout_weeks",
    sortOrder: 892,
  },
  {
    key: "kit_complete",
    name: "Kit Complete",
    description: "Opened five checkouts built from a saved kit.",
    icon: "PackageOpen",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "checkout_from_kit",
    sortOrder: 894,
  },
  {
    key: "short_notice",
    name: "Short Notice",
    description: "Claimed three shift trades inside the last day before the shift started.",
    icon: "AlarmClock",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "trade:completed",
    threshold: 3,
    ruleKey: "trade_short_notice",
    sortOrder: 865,
  },
  {
    key: "long_haul",
    name: "Long Haul",
    description: "Returned five checkouts held a week or longer with nothing damaged or missing.",
    icon: "Truck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 5,
    ruleKey: "return_long_haul",
    sortOrder: 896,
  },
  {
    key: "round_trip",
    name: "Round Trip",
    description: "Opened and returned twenty-five checkouts inside the same day.",
    icon: "ArrowLeftRight",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 25,
    ruleKey: "return_same_day",
    sortOrder: 898,
  },
  {
    key: "go_to_bed",
    name: "Go To Bed",
    description: "Opened the app during the 2 a.m. hour. Seriously, go to bed.",
    icon: "MoonStar",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "app:opened",
    threshold: null,
    ruleKey: "local_hour_2",
    sortOrder: 900,
  },
  {
    key: "old_faithful",
    name: "Old Faithful",
    description: "Checked out the same item 25 times.",
    icon: "Camera",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 25,
    ruleKey: "checkout_same_asset",
    sortOrder: 905,
  },
  {
    key: "battery_run",
    name: "Battery Run",
    description: "Opened five checkouts containing nothing but batteries.",
    icon: "BatteryLow",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "checkout_batteries_only",
    sortOrder: 910,
  },
  {
    key: "buzzer_beater",
    name: "Buzzer Beater",
    description: "Returned three checkouts in the last five minutes before they were due.",
    icon: "Timer",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 3,
    ruleKey: "return_buzzer_beater",
    sortOrder: 915,
  },
  {
    key: "take_thirteen",
    name: "Take Thirteen",
    description: "Opened the app on a Friday the 13th.",
    icon: "Clapperboard",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "app:opened",
    threshold: null,
    ruleKey: "local_friday_13",
    sortOrder: 920,
  },
  {
    key: "holiday_hours",
    name: "Holiday Hours",
    description: "Opened the app on December 25 or January 1. The season does not stop.",
    icon: "Gift",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "app:opened",
    threshold: null,
    ruleKey: "local_holiday",
    sortOrder: 925,
  },
  {
    key: "plan_ahead",
    name: "Plan Ahead",
    description: "Picked up five reservations at the counter.",
    icon: "CalendarCheck2",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "checkout_from_reservation",
    sortOrder: 1500,
  },
  {
    key: "crew_checkout",
    name: "Crew Checkout",
    description: "Opened five checkouts tied to a scheduled crew assignment.",
    icon: "PackageCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "checkout_for_shift",
    sortOrder: 1510,
  },
  {
    key: "checkout_sprint",
    name: "Burst Mode",
    description: "Opened five gear checkouts in one local calendar week.",
    icon: "PackageCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "checkout_week_burst",
    sortOrder: 1000,
  },
  {
    key: "checkout_calendar",
    name: "Calendar Commitment",
    description: "Opened checkouts in 12 different local calendar months.",
    icon: "CalendarRange",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 12,
    ruleKey: "checkout_months",
    sortOrder: 1010,
  },
  {
    key: "on_time_clean",
    name: "Clean Timing",
    description: "Returned 20 checkouts on time with no check-in reports.",
    icon: "ShieldCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 20,
    ruleKey: "return_on_time_clean",
    sortOrder: 1020,
  },
  {
    key: "return_steady",
    name: "Steady Hands",
    description: "Returned 15 consecutive checkouts on time and report-free.",
    icon: "Flame",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 15,
    ruleKey: "return_clean_streak",
    sortOrder: 1030,
  },
  {
    key: "category_combo",
    name: "Category Crossfade",
    description: "Opened three checkouts spanning at least four item categories each.",
    icon: "LayoutGrid",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 3,
    ruleKey: "checkout_categories_4",
    sortOrder: 1040,
  },
  {
    key: "return_no_intervention",
    name: "No Follow-Ups",
    description: "Returned 25 checkouts with no reports and no due-date changes.",
    icon: "BadgeCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 25,
    ruleKey: "return_no_intervention",
    sortOrder: 1050,
  },
  {
    key: "shift_cross_training",
    name: "Cross-Trained",
    description: "Covered eight distinct sport-and-crew-area combinations.",
    icon: "Shuffle",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 8,
    ruleKey: "shift_sport_area_pairs",
    sortOrder: 1060,
  },
  {
    key: "shift_schedule_span",
    name: "Calendar Crew",
    description: "Was assigned to completed shifts in six different local months.",
    icon: "CalendarRange",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 6,
    ruleKey: "shift_months",
    sortOrder: 1070,
  },
  {
    key: "trade_two_way",
    name: "Two-Way Teammate",
    description: "Completed trades both as a poster and as a claimant.",
    icon: "Handshake",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "trade:completed",
    threshold: 1,
    ruleKey: "trade_both_sides",
    sortOrder: 1080,
  },
  {
    key: "family_archivist",
    name: "Family Archivist",
    description: "Checked out gear from eight different gear families.",
    icon: "Warehouse",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 8,
    ruleKey: "checkout_distinct_families",
    sortOrder: 1090,
  },
  {
    key: "battery_bank",
    name: "Battery Bank",
    description: "Checked out gear with batteries 25 times.",
    icon: "BatteryCharging",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 25,
    ruleKey: "checkout_family_batteries",
    sortOrder: 1100,
  },
  {
    key: "lens_library",
    name: "Lens Library",
    description: "Checked out lenses 25 times.",
    icon: "Aperture",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 25,
    ruleKey: "checkout_family_lenses",
    sortOrder: 1110,
  },
  {
    key: "audio_aisle",
    name: "Audio Aisle",
    description: "Checked out audio gear 15 times.",
    icon: "AudioLines",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 15,
    ruleKey: "checkout_family_audio",
    sortOrder: 1120,
  },
  {
    key: "lighting_grid",
    name: "Lighting Grid",
    description: "Checked out lighting gear ten times.",
    icon: "Lightbulb",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 10,
    ruleKey: "checkout_family_lighting",
    sortOrder: 1130,
  },
  {
    key: "family_mixer",
    name: "Family Mixer",
    description: "Opened five checkouts spanning five or more gear families.",
    icon: "LayoutGrid",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "checkout_families_5",
    sortOrder: 1140,
  },
  {
    key: "full_rig_heavy",
    name: "Full Rig, Full Load",
    description: "Opened three full-rig checkouts carrying at least ten pieces each.",
    icon: "Combine",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 3,
    ruleKey: "checkout_full_rig_heavy",
    sortOrder: 1150,
  },
  {
    key: "gear_volume_150",
    name: "Warehouse Shift",
    description: "Moved 150 actual gear pieces through credited checkouts.",
    icon: "Dumbbell",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 150,
    ruleKey: "checkout_item_volume",
    sortOrder: 1160,
  },
  {
    key: "mixed_inventory",
    name: "Mixed Inventory",
    description: "Opened five checkouts containing both serialized and bulk gear.",
    icon: "Boxes",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "checkout_mixed_inventory",
    sortOrder: 1170,
  },
  {
    key: "kit_variety",
    name: "Kit Collector",
    description: "Opened checkouts built from three different saved kits.",
    icon: "PackageOpen",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 3,
    ruleKey: "checkout_distinct_kits",
    sortOrder: 1180,
  },
  {
    key: "checkout_month_streak",
    name: "Month-to-Month",
    description: "Opened checkouts in four consecutive local calendar months.",
    icon: "CalendarCheck2",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 4,
    ruleKey: "checkout_consecutive_months",
    sortOrder: 1190,
  },
  {
    key: "home_and_away",
    name: "Home and Away",
    description: "Was assigned to both home and away completed events.",
    icon: "Ticket",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 1,
    ruleKey: "shift_home_and_away",
    sortOrder: 1200,
  },
  {
    key: "schedule_spectrum",
    name: "Schedule Spectrum",
    description: "Covered at least five sports across at least three crew areas.",
    icon: "Shuffle",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 1,
    ruleKey: "shift_spectrum",
    sortOrder: 1210,
  },
  {
    key: "away_win",
    name: "Road Win",
    description: "Was assigned to three completed away events recorded as wins.",
    icon: "Trophy",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 3,
    ruleKey: "shift_away_wins",
    sortOrder: 1220,
  },
  {
    key: "result_site_sweep",
    name: "Three-Site Scoreboard",
    description: "Worked recorded wins at home, away, and a neutral site.",
    icon: "Trophy",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 1,
    ruleKey: "shift_result_sites",
    sortOrder: 1230,
  },
  {
    key: "long_day_crew",
    name: "Long-Day Crew",
    description: "Had at least three early calls and five late finishes.",
    icon: "Sunset",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 1,
    ruleKey: "shift_early_late_mix",
    sortOrder: 1240,
  },
  {
    key: "reservation_event",
    name: "Reserved for Game Day",
    description: "Opened three reservation checkouts tied to scheduled events.",
    icon: "CalendarClock",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 3,
    ruleKey: "checkout_reserved_event",
    sortOrder: 1250,
  },
  {
    key: "distinct_event_loadout",
    name: "Event Roster",
    description: "Opened credited checkouts linked to ten distinct scheduled events.",
    icon: "CalendarCheck2",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 10,
    ruleKey: "checkout_distinct_events",
    sortOrder: 1260,
  },
  {
    key: "multi_event",
    name: "Multi-Event Loadout",
    description: "Opened five checkouts linked to two or more scheduled events.",
    icon: "Combine",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 5,
    ruleKey: "checkout_multiple_events",
    sortOrder: 1270,
  },
  {
    key: "full_context_loadout",
    name: "Full Context Loadout",
    description: "Opened three checkouts tied to a reservation, event, and crew assignment.",
    icon: "Cable",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 3,
    ruleKey: "checkout_full_context",
    sortOrder: 1280,
  },
  {
    key: "shift_loadout_heavy",
    name: "Crew Loadout Pro",
    description: "Opened three shift-linked checkouts carrying at least ten pieces each.",
    icon: "PackageCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:opened",
    threshold: 3,
    ruleKey: "checkout_for_shift_heavy",
    sortOrder: 1290,
  },
  {
    key: "result_sweep",
    name: "Scoreboard Across Sports",
    description: "Worked events with recorded results in four different sports.",
    icon: "BadgeCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 4,
    ruleKey: "shift_scored_sports",
    sortOrder: 1300,
  },
  {
    key: "winning_record",
    name: "Winning Record",
    description: "Worked at least eight decided events with more wins than losses.",
    icon: "Trophy",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 1,
    ruleKey: "shift_winning_record",
    sortOrder: 1310,
  },
  {
    key: "win_streak",
    name: "Hot Streak",
    description: "Worked five consecutive events recorded as wins.",
    icon: "Flame",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 5,
    ruleKey: "shift_win_streak",
    sortOrder: 1320,
  },
  {
    key: "bounce_back",
    name: "Bounce Back",
    description: "Worked a recorded win after a recorded loss.",
    icon: "Repeat2",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 1,
    ruleKey: "shift_bounce_back",
    sortOrder: 1330,
  },
  {
    key: "battle_tested",
    name: "Battle Tested",
    description: "Worked at least three wins and three losses across the schedule.",
    icon: "ShieldCheck",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 1,
    ruleKey: "shift_battle_tested",
    sortOrder: 1340,
  },
  {
    key: "home_field",
    name: "Home Field",
    description: "Was assigned to 15 completed events at a recorded home site.",
    icon: "Ticket",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 15,
    ruleKey: "shift_home",
    sortOrder: 1350,
  },
  {
    key: "neutral_ground",
    name: "Neutral Ground",
    description: "Was assigned to five completed neutral-site events.",
    icon: "Binoculars",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 5,
    ruleKey: "shift_neutral",
    sortOrder: 1360,
  },
  {
    key: "venue_hopper",
    name: "Venue Hopper",
    description: "Was assigned to completed events at seven different mapped venues.",
    icon: "Warehouse",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 7,
    ruleKey: "shift_venues",
    sortOrder: 1370,
  },
  {
    key: "venue_regular",
    name: "Venue Regular",
    description: "Was assigned to 15 completed events at the same mapped venue.",
    icon: "ShoppingCart",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 15,
    ruleKey: "shift_same_venue",
    sortOrder: 1380,
  },
  {
    key: "opponent_rollcall",
    name: "Opponent Rollcall",
    description: "Was assigned to completed events against seven different opponents.",
    icon: "Handshake",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 7,
    ruleKey: "shift_opponents",
    sortOrder: 1390,
  },
  {
    key: "rivalry_rematch",
    name: "Rivalry Rematch",
    description: "Was assigned to five completed events against the same opponent.",
    icon: "Repeat2",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 5,
    ruleKey: "shift_same_opponent",
    sortOrder: 1400,
  },
  {
    key: "site_sweep",
    name: "Three-Site Tour",
    description: "Was assigned to home, away, and neutral completed events.",
    icon: "Binoculars",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 3,
    ruleKey: "shift_sites",
    sortOrder: 1410,
  },
  {
    key: "oops_damaged",
    name: "Oops, That Was Damaged",
    description: "Returned a checkout with a recorded damage report. It happens.",
    icon: "CloudRain",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 1,
    ruleKey: "return_damaged",
    sortOrder: 1420,
  },
  {
    key: "oops_missing",
    name: "Where Did That Go?",
    description: "Returned a checkout with a recorded missing-item report.",
    icon: "ShoppingCart",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 1,
    ruleKey: "return_missing",
    sortOrder: 1430,
  },
  {
    key: "running_late",
    name: "Running Late",
    description: "Returned five checkouts more than 15 minutes after they were due.",
    icon: "AlarmClock",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 5,
    ruleKey: "return_late",
    sortOrder: 1440,
  },
  {
    key: "due_date_dancer",
    name: "Due Date Dancer",
    description: "Had the due date changed on three completed checkouts.",
    icon: "CalendarClock",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "checkout:returned",
    threshold: 3,
    ruleKey: "return_due_date_changed",
    sortOrder: 1450,
  },
  {
    key: "calendar_tetris",
    name: "Calendar Tetris",
    description: "Was assigned to five completed shifts that carried a recorded conflict.",
    icon: "CalendarDays",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.COUNT,
    trigger: "shift:completed",
    threshold: 5,
    ruleKey: "shift_conflicts",
    sortOrder: 1460,
  },
  {
    key: "midnight_oil",
    name: "Midnight Oil",
    description: "Opened the app during the midnight hour.",
    icon: "MoonStar",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "app:opened",
    threshold: null,
    ruleKey: "local_hour_0",
    sortOrder: 1470,
  },
  {
    key: "weekend_warrior",
    name: "Weekend Warrior",
    description: "Opened the app on a Saturday or Sunday.",
    icon: "Sparkles",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "app:opened",
    threshold: null,
    ruleKey: "local_weekend",
    sortOrder: 1480,
  },
  {
    key: "leap_day",
    name: "Leap Day",
    description: "Opened the app on February 29.",
    icon: "Clapperboard",
    category: BadgeCategory.MILESTONE,
    kind: BadgeKind.RULE,
    trigger: "app:opened",
    threshold: null,
    ruleKey: "local_leap_day",
    sortOrder: 1490,
  },
];

async function main() {
  // Rename legacy locations
  for (const [oldName, newName] of Object.entries(legacyNames)) {
    const existing = await prisma.location.findUnique({ where: { name: oldName } });
    if (existing) {
      // Only rename if the new name doesn't already exist
      const newExists = await prisma.location.findUnique({ where: { name: newName } });
      if (!newExists) {
        await prisma.location.update({ where: { name: oldName }, data: { name: newName, isHomeVenue: true } });
      }
    }
  }

  // Upsert all home venues
  for (const name of homeVenues) {
    await prisma.location.upsert({
      where: { name },
      create: { name, isHomeVenue: true },
      update: { isHomeVenue: true },
    });
  }

  // Upsert support facilities (not home venues)
  for (const name of supportFacilities) {
    await prisma.location.upsert({
      where: { name },
      create: { name, isHomeVenue: false },
      update: {},
    });
  }

  // ── Venue mapping patterns (ICS location text → Location) ──
  // Each pattern is matched against event venue text during calendar sync.
  // Multiple patterns can map to the same location for flexibility.
  // Only event facilities get venue mappings (not training/support buildings)
  const venueMappings = [
    { patterns: ["Camp Randall"],                          location: "Camp Randall Stadium" },
    { patterns: ["Kohl Center"],                           location: "Kohl Center" },
    { patterns: ["Field House", "UW Field House"],         location: "UW Field House" },
    { patterns: ["LaBahn"],                                location: "LaBahn Arena" },
    { patterns: ["Goodman", "Softball Complex"],           location: "Goodman Softball Complex" },
    { patterns: ["Porter Boathouse", "Boathouse"],         location: "Porter Boathouse" },
    { patterns: ["McClimon"],                              location: "McClimon Track/Soccer Complex" },
    { patterns: ["Soderholm", "Aquatic Center"],           location: "Soderholm Family Aquatic Center" },
    { patterns: ["Nielsen Tennis", "Nielsen Stadium"],     location: "Nielsen Tennis Stadium" },
    { patterns: ["University Ridge"],                      location: "University Ridge" },
    { patterns: ["Zimmer", "Championship Course"],         location: "Zimmer Championship Course" },
  ];

  for (const { patterns, location: locationName } of venueMappings) {
    const loc = await prisma.location.findUnique({ where: { name: locationName } });
    if (!loc) continue;
    for (const pattern of patterns) {
      await prisma.locationMapping.upsert({
        where: { id: `seed-${pattern.toLowerCase().replace(/\s+/g, "-")}` },
        create: {
          id: `seed-${pattern.toLowerCase().replace(/\s+/g, "-")}`,
          pattern,
          locationId: loc.id,
          priority: 10,
        },
        update: {
          pattern,
          locationId: loc.id,
          priority: 10,
        },
      });
    }
  }

  const campRandall = await prisma.location.findFirst({
    where: { name: { startsWith: "Camp Randall" } }
  }) ?? await prisma.location.findFirstOrThrow({});

  const adminPassword = process.env.SEED_ADMIN_PASSWORD || "ChangeMeNow123!";
  const passwordHash = await bcrypt.hash(adminPassword, 10);

  await prisma.user.upsert({
    where: { email: "admin@creative.local" },
    create: {
      name: "Creative Admin",
      email: "admin@creative.local",
      passwordHash,
      role: Role.ADMIN,
      locationId: campRandall.id,
      hiddenFromRoster: true,
    },
    update: {
      passwordHash,
      role: Role.ADMIN,
      locationId: campRandall.id,
      hiddenFromRoster: true,
    }
  });

  await prisma.systemConfig.upsert({
    where: { key: "badges.peerVisible" },
    create: { key: "badges.peerVisible", value: true },
    update: {},
  });

  for (const definition of badgeDefinitions) {
    await prisma.badgeDefinition.upsert({
      where: { key: definition.key },
      create: definition,
      update: {
        name: definition.name,
        description: definition.description,
        icon: definition.icon,
        category: definition.category,
        kind: definition.kind,
        trigger: definition.trigger,
        threshold: definition.threshold,
        ruleKey: definition.ruleKey ?? null,
        active: definition.active ?? true,
        sortOrder: definition.sortOrder,
      },
    });
  }

  console.log("Seed complete: admin@creative.local");
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
